// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "HomePage": {
    "title": "posts",
    "welcome-message": "Welcome to the Posts!",
    "description": "Discover amazing content and share your thoughts."
  },
  "Header": {
    "home": "Home",
    "pq": "PostsPQ",
    "iq": "PostsIQ",
    "blogs": "Blogs",
    "add-post": "Add Post",
    "add-blog": "Add Blog"
  },
  "LocaleSwitcher": {
    "label": "Change language",
    "locale": "{locale, select, ru {🇷🇺 russian} en {🇺🇸 English} other {Unknown}}"
  },
  "PostCard": {
    "read-more": "Read More"
  }
};
export default messages;